verbose: true
go:
    version: 1.17
    cgo: false
repository:
   path: github.com/f100024/syncthing_exporter
build:
    prefix: out/
    binaries:
        - name: syncthing_exporter
    flags: -a -tags netgo
    ldflags: |
        -s
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser=local
        -X 'github.com/prometheus/common/version.BuildDate={{date "02 Jan 2006 15:04:05 MST"}}'
tarball:
    prefix: .
    files:
        - syncthing_exporter
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - aix/ppc64
        - darwin/amd64
        - darwin/arm64
        - dragonfly/amd64
        - freebsd/386
        - freebsd/amd64
        - freebsd/arm64
        - freebsd/armv6
        - freebsd/armv7
        - illumos/amd64
        - linux/386
        - linux/amd64
        - linux/arm64
        - linux/armv5
        - linux/armv6
        - linux/armv7
        - linux/mips
        - linux/mips64
        - linux/mips64le
        - linux/mipsle
        - linux/ppc64
        - linux/ppc64le
        - linux/s390x
        - netbsd/386
        - netbsd/amd64
        - netbsd/arm64
        - netbsd/armv6
        - netbsd/armv7
        - openbsd/386
        - openbsd/amd64
        - openbsd/arm64
        - openbsd/armv7
        - windows/386
        - windows/amd64
