
name: Make release

on:
  workflow_dispatch:
    make_release:
      description: Create draft of release on github
      default: true
      type: boolean
      required: true
    build_dockerimage:
      description: Build docker images and push to docker hub
      default: true
      type: boolean
      required: true
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-22.04
    env:
      GOPATH: /home/runner/go
    steps:
 
      - name: Checkout code
        uses: actions/checkout@v3.1.0
  
      - name: Make crossbuild
        run: make crossbuild
 
      - name: Make tarballs
        run: make tarballs
 
      - name: Upload files to release
        if: ${{ inputs.make_release }}
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: .build
          key: syncthing_exporter-${{ github.sha }}

  build_dockerimage:
    if: ${{ inputs.build_dockerimage }}
    needs: build_release
    name: Build docker images
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Set VERSION as environment variable
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "TAG=$(cat VERSION)" >> $GITHUB_ENV

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: .build
          key: syncthing_exporter-${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          pull: true
          files: docker-bake-release.hcl
          targets: release
