
name: Make release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-20.04
    env:
      GOPATH: /home/runner/go
    steps:
 
      - name: Checkout code
        uses: actions/checkout@v3.0.2
 
      - name: Install promu
        run:  |
          mkdir -p $GOPATH
          wget --quiet https://github.com/prometheus/promu/releases/download/v0.13.0/promu-0.13.0.linux-amd64.tar.gz
          tar -C $GOPATH -xzf promu-0.13.0.linux-amd64.tar.gz
 
      - name: Make crossbuild
        run: make crossbuild
 
      - name: Make tarballs
        run: make tarballs
 
      - name: Upload files to release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_dockerimage:
    name: Build docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Set VERSION as environment variable
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/syncthing_exporter:latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/syncthing_exporter:${{ env.VERSION }}
